name: Configurar Switches

on:
  push:
    branches:
      - main

jobs:
  runner:
    runs-on: self-hosted
      
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      
    - name: Copiar arquivo com valores substituídos para /tftp no runner
      run: yes | cp -rf config/poc-config /tftp
      
      env:
        TFTP_FILE: /tftp/poc-config

    - name: Transferir arquivo para o servidor TFTP
      run: scp /tftp/poc-config user@192.168.15.100:/tftpboot/
      env:
        TFTP_SERVER: 192.168.15.100
        TFTP_USER: user
        TFTP_PASSWORD: admin123

    - name: Executar script para aplicar configuração no switch
      run: python3 config/switches/script-apply.py