name: Configurar Switches

on:
  push:
    branches:
      - main

jobs:
  runner:
    runs-on: self-hosted
      
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Configurar ambiente virtual e instalar dependências Python
      run: |
        python3 -m venv venv
        source venv/bin/activate
        python3 -m pip install --upgrade pip
        pip install -r requirements.txt
      
    - name: Copiar arquivo com valores substituídos para /tftp no runner
      run: yes | cp -rf config/poc-config /tftp
      
      env:
        TFTP_FILE: /tftp/poc-config

    - name: Copiar arquivo para o diretório do servidor TFTP
      run: echo "$SUDO_PASSWORD" | sudo -S cp /tftp/poc-config /tftpboot/
      env:
        SUDO_PASSWORD: admin123

    - name: Executar script para aplicar configuração no switch
      run: python3 config/script-apply.py