name: Configurar Switches

on:
  push:
    branches:
      - main

jobs:
  runner:
    runs-on: self-hosted
      
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      
    - name: Copiar arquivo com valores substituídos para /tftp no runner
      run: yes | cp -rf config/poc-config /tftp
      
      env:
        TFTP_FILE: /tftp/poc-config

    - name: Copiar arquivo para o diretório do servidor TFTP
      run: sudo cp /tftp/poc-config /tftpboot/

    - name: Executar script para aplicar configuração no switch
      run: python3 config/switches/script-apply.py