name: Configurar Switches

on:
  push:
    branches:
      - main

jobs:
  runner:
    runs-on: self-hosted
      
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Configurar ambiente virtual e instalar dependências Python
      run: |
        python3 -m venv venv
        source venv/bin/activate
        python3 -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Executar script para aplicar configuração no switch
      run: |
        source venv/bin/activate
        python3 config/script-apply.py